# python script to check all roles

import os
import subprocess

playbook = "playbook-test.yml"
ls_roles = "ls roles"
content = []
roles_output = subprocess.check_output(ls_roles, shell=True)
roles = roles_output.split('\n')


try:
	target = open(playbook, 'w') 
except IOError:
	sys.exit("error in opening file")

content.append("---\n")
content.append('# test playbook\n')
content.append("- name: autogenerated playbook \n")
content.append("  hosts: localhost\n")
content.append("  roles:\n")

for role in roles:
    if role:
        content.append("    - " + role + '\n')  
        #print "role is " + role

for str in content: 
    target.write(str)

target.close()

run_playbook = 'ansible-playbook playbook-test.yml --syntax-check'
subprocess.call(run_playbook, shell=True)